name: my_animated_tabs
description: A highly-customizable Flutter TabContainer with buttery-smooth animated transitions.
version: 1.0.2

homepage:   https://github.com/Sunilnani/animated_tabs_package
repository: https://github.com/Sunilnani/animated_tabs_package
issue_tracker: https://github.com/Sunilnani/animated_tabs_package/issues
license: MIT

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"     # 3.x guarantees Material 3 & Impeller fixes

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter           # keeps the default test harness available
  flutter_lints: ^3.0.1    # â† official lint rules used by most packages

flutter:
  assets:
    - assets/screenshotone.jpeg
    - assets/demo.gif
